Repository Decide-chiquito/decide-part-chiquito, pull requests merged in 2023-12, with the labels that each got.

#112 Fix: Postproc naming
  decide/postproc/tests.py
  decide/postproc/views.py
  decide/visualizer/templates/visualizer/visualizer.html
  decide/visualizer/templates/visualizer/visualizer_mobile.html
  decide/voting/admin.py
  decide/voting/models.py
  decide/voting/serializers.py
Labels: Chiquito-1, Refactor

#121 Fix: Header in responsive is shown propertly
  decide/base/templates/base.html
  decide/base/templates/initial_mobile.html
  decide/base/views.py
  decide/visualizer/templates/visualizer/visualizer_mobile.html
  decide/visualizer/views.py
Labels: bug, Chiquito-1, Interface

#122 fix import and export to csv
  decide/voting/admin.py
  decide/voting/templates/csv_upload.html
Labels: bug, Chiquito-1

#131 feat send email when census is created
  decide/census/admin.py
  decide/census/models.py
  decide/voting/admin.py
Labels: enhancement, Chiquito-1

#102 test añadidos test para el inicio de sesión con correo
  decide/users/tests.py
Labels: Chiquito-1, Test

#124 test añadidas pruebas para la visualización de gráficas
  decide/visualizer/tests.py
Labels: Chiquito-1, Test

#126 Fix: gitignore updated
  .gitignore
  decide/base/migrations/0001_initial.py
  decide/base/migrations/0002_auto_20180921_1056.py
  decide/base/migrations/0003_auto_20180921_1119.py
  decide/census/migrations/0001_initial.py
  decide/census/migrations/0002_census_adscription_center.py
  decide/census/migrations/0003_tag_census_tags.py
  decide/mixnet/migrations/0001_initial.py
  decide/mixnet/migrations/0002_auto_20180216_1617.py
  decide/mixnet/migrations/0003_mixnet_auth_position.py
  decide/mixnet/migrations/0004_auto_20180605_0842.py
  decide/store/migrations/0001_initial.py
  decide/store/migrations/0002_vote_voted.py
  decide/store/migrations/0003_auto_20180921_1522.py
  decide/voting/migrations/0001_initial.py
  decide/voting/migrations/0002_auto_20180302_1100.py
  decide/voting/migrations/0003_auto_20180605_0842.py
  decide/voting/migrations/0004_alter_voting_postproc_alter_voting_tally.py
  decide/voting/migrations/0005_voting_seats_voting_type.py
  decide/voting/migrations/0006_alter_voting_type.py
Labels: bug, Chiquito-1

#136 test import census to csv
  decide/census/tests.py
Labels: Chiquito-1, Test

#150 Feat: Update responsive interface with new adapted functionalities
  decide/base/static/css/style.css
  decide/base/templates/initial_mobile.html
  decide/visualizer/static/visualizer/style.css
  decide/visualizer/templates/visualizer/visualizer_mobile.html
  decide/voting/admin.py
  decide/voting/static/voting/modal.js
  decide/voting/static/voting/style.css
  decide/voting/templates/csv_upload_mobile.html
Labels: Chiquito-1, Interface

#148 Fix: Change register redirection
  decide/users/templates/registration/register_fail.html
  decide/users/templates/registration/register_success.html
  decide/users/tests.py
  decide/users/views.py
Labels: Chiquito-1, Test, Interface

#143 test añadidas pruebas al login con certificado digital
  decide/cert.pem
  decide/cert.pfx
  decide/key.pem
  decide/users/tests.py
Labels: Chiquito-1, Test

#118 Feat/list voting user
  .github/workflows/django.yml
  decide/base/templates/initial.html
  decide/booth/templates/booth/listBooth.html
  decide/booth/tests.py
  decide/booth/urls.py
  decide/booth/views.py
  decide/visualizer/templates/visualizer/listVisualizer.html
  decide/visualizer/tests.py
  decide/visualizer/urls.py
  decide/visualizer/views.py
Labels: enhancement, Chiquito-2, Test

#94 Feat/audition
  decide/base/models.py
  decide/census/models.py
  decide/decide/settings.py
  decide/store/models.py
  decide/voting/models.py
  decide/voting/tests.py
  docker/Dockerfile
  requirements.txt
Labels: enhancement, Chiquito-2

#137 Test: Send email when census is created
  decide/census/models.py
  decide/census/tests.py
  decide/voting/models.py
Labels: Chiquito-1, Test

#151 Feat: Responsive interface for register and login
  decide/users/static/users/style.css
  decide/users/templates/registration/cert_login_mobile.html
  decide/users/templates/registration/make_petition_form_mobile.html
  decide/users/templates/users/login_mobile.html
  decide/users/templates/users/register_mobile.html
  decide/users/views.py
Labels: Chiquito-1, Interface

#157 feat live statistics done
  decide/visualizer/templates/visualizer/visualizer.html
  decide/visualizer/views.py
  decide/voting/models.py
Labels: enhancement, Chiquito-1

#97 fix: Docker populate #95
  docker/docker-compose.yml
Labels: enhancement, Chiquito-2

#162 Revert "fix: Docker populate #95"
  docker/docker-compose.yml
Labels: invalid, Chiquito-2

#159 Feat: Responsive booth interface
  decide/booth/static/booth/modal.js
  decide/booth/static/booth/style_mobile.css
  decide/booth/templates/booth/booth_mobile.html
  decide/booth/views.py
Labels: Chiquito-1, Interface

#149 feat yes/no question for votations
  decide/base/templates/initial.html
  decide/base/templates/initial_mobile.html
  decide/booth/templates/booth/booth.html
  decide/booth/views.py
  decide/visualizer/templates/visualizer/visualizer.html
  decide/visualizer/views.py
  decide/voting/admin.py
  decide/voting/models.py
  decide/voting/static/voting/admin/form.js
Labels: enhancement, Chiquito-1

#164 Fix: Changed datetime and fixed census test
  decide/booth/tests.py
  decide/census/tests.py
  decide/visualizer/tests.py
  decide/voting/models.py
Labels: bug, Chiquito-1

#163 Feat: mail voting
  decide/voting/admin.py
  decide/voting/templates/start_email_template.html
  decide/voting/templates/tally_email_template.html
Labels: enhancement, Chiquito-1

#168 test Reuse census tests uploaded
  decide/voting/tests.py
Labels: Chiquito-1, Test

#167 fix error when show live statistics
  decide/visualizer/templates/visualizer/visualizer.html
  decide/visualizer/views.py
  decide/voting/admin.py
Labels: bug, Chiquito-1

#165 Feat: Edit user profile
  decide/base/templates/initial.html
  decide/base/templates/initial_mobile.html
  decide/users/static/users/style.css
  decide/users/templates/users/edit_profile.html
  decide/users/templates/users/edit_profile_mobile.html
  decide/users/urls.py
  decide/users/views.py
Labels: enhancement, Chiquito-1

#174 Fix Import census limited for admins Fixes #173
  decide/base/templates/initial.html
  decide/voting/admin.py
Labels: Chiquito-1, Interface

#179 fix: test bugs
  decide/base/tests.py
  decide/census/tests.py
  decide/voting/admin.py
Labels: bug, Chiquito-1

#177 refactor correción algunas de mis issues de codacy
  decide/booth/tests.py
  decide/census/tests.py
  decide/mixnet/mixcrypt.py
  decide/mixnet/models.py
  decide/mixnet/views.py
  decide/postproc/tests.py
  decide/postproc/views.py
  decide/store/tests.py
  decide/store/urls.py
  decide/users/tests.py
  decide/visualizer/tests.py
  decide/visualizer/views.py
  decide/voting/admin.py
  decide/voting/models.py
  decide/voting/tests.py
  decide/voting/views.py
Labels: Chiquito-1, Refactor

#170 Test Voting Yes/No
  decide/visualizer/tests.py
  decide/voting/tests.py
Labels: Chiquito-1, Test

#181 fix Solved redirection problem
  decide/users/templates/registration/cert_login.html
  decide/users/templates/registration/cert_success.html
  decide/users/templates/registration/register_success.html
Labels: bug, Chiquito-1

#158 feat boton para login y logout #156
  decide/base/templates/initial.html
  decide/base/views.py
  decide/users/views.py
Labels: enhancement, Chiquito-2

#184 feat voting admin test
  decide/voting/tests.py
Labels: Chiquito-1, Test

#141 Feat / export census tests
  decide/voting/tests.py
Labels: Chiquito-1, Test

#187 Test: User testing from mobile view
  decide/users/templates/users/edit_profile_mobile.html
  decide/users/templates/users/login_mobile.html
  decide/users/templates/users/register_mobile.html
  decide/users/tests.py
Labels: Chiquito-1, Test

#188 feat edit users static test done
  decide/users/templates/users/edit_profile.html
  decide/users/tests.py
  decide/users/views.py
Labels: Chiquito-1, Test

#191 Fix: Login and logout buttons now appear in responsive menu
  decide/base/templates/initial_mobile.html
  decide/booth/static/booth/style_mobile.css
Labels: Chiquito-1, Interface

#192 Feat: Add workflows
  .github/workflows/analyse_with_devskim.yml
  .github/workflows/analyse_with_qodana.yml
  .github/workflows/create_changelog.yml
  .github/workflows/dependecy_review.yml
  .github/workflows/django.yml
Labels: enhancement, Chiquito-2

#194 Refactor duplicated imports
  decide/users/views.py
Labels: Chiquito-1, Refactor

#198 fix docker now clones master
  docker/Dockerfile
Labels: Chiquito-1, Configuration

#199 Refactor alejandrocg024 codacy issues
  decide/visualizer/views.py
  decide/voting/admin.py
  decide/voting/tests.py
Labels: Chiquito-1, Refactor

#202 Feat/test show live statistics
  decide/visualizer/tests.py
Labels: Chiquito-1, Test

#204 Fix/vagrant deploy
  decide/users/templates/users/login.html
  vagrant/django.yml
Labels: bug, Chiquito-1

#110 Feat Script construction
  docker/Dockerfile
  docker/Dockerfile-nginx
  docker/docker-compose.yml
  docker/docker-nginx.conf
  docker/docker-settings.py
Labels: enhancement, Chiquito-2

#205 test email start voting
  decide/voting/tests.py
Labels: Chiquito-1, Test

#206 Feat/web inbox
  decide/base/backends.py
  decide/base/templates/initial.html
  decide/populate.json
  decide/users/static/users/style.css
  decide/users/templates/users/notice.html
  decide/users/test_selenium.py
  decide/users/urls.py
  decide/users/views.py
Labels: enhancement, Chiquito-2

#213 Fix: test_filtrofecha #212
  decide/test-scripts/cert.pfx
  decide/test-scripts/invalid_file.txt
  decide/users/test_selenium.py
Labels: bug, Chiquito-2

#217 doc documentation finished
  doc/Documento de gestión de equipos.pdf
  doc/Documento de gestión de la construcción.pdf
  doc/Documento de gestión de la entrega y el despliegue.pdf
  doc/Documento de gestión de la integración continua.pdf
  doc/Documento de gestión del código.pdf
  doc/Documento de la gestión de las incidencias.pdf
  doc/Documento para la realización y automatización de pruebas.pdf
Labels: documentation, Chiquito-2, Chiquito-1

#214 fix: bug lista votaciones activas
  .github/workflows/django.yml
  decide/authentication/admin.py
  decide/booth/views.py
  decide/voting/admin.py
Labels: bug, Chiquito-2

#220 hotfix certificate username
  decide/users/forms.py
Labels: bug, Chiquito-1

#222 Hotfix: Add test notice
  decide/users/test_selenium.py
Labels: Chiquito-2, Test

#111 Feat Multiple Questions
  decide/base/mods.py
  decide/base/templates/base.html
  decide/booth/templates/booth/booth.html
  decide/booth/tests.py
  decide/booth/views.py
  decide/census/tests.py
  decide/mixnet/mixcrypt.py
  decide/mixnet/views.py
  decide/populate.json
  decide/store/admin.py
  decide/store/models.py
  decide/store/serializers.py
  decide/store/tests.py
  decide/store/views.py
  decide/users/views.py
  decide/visualizer/templates/visualizer/visualizer.html
  decide/visualizer/tests.py
  decide/visualizer/views.py
  decide/voting/management/commands/testvoting.py
  decide/voting/models.py
  decide/voting/serializers.py
  decide/voting/tests.py
  decide/voting/views.py
Labels: enhancement, Chiquito-2

#226 docs fix doc gestion incidencias
  doc/Documento de la gestión de las incidencias.pdf
Labels: documentation, Chiquito-2

#227 fix: Bug Multiple Objects Return
  decide/users/views.py
Labels: bug, Chiquito-2

#228 Hotfix
  .github/workflows/django.yml
  decide/authentication/admin.py
  decide/base/mods.py
  decide/base/templates/base.html
  decide/booth/templates/booth/booth.html
  decide/booth/tests.py
  decide/booth/views.py
  decide/census/tests.py
  decide/mixnet/mixcrypt.py
  decide/mixnet/views.py
  decide/populate.json
  decide/store/admin.py
  decide/store/models.py
  decide/store/serializers.py
  decide/store/tests.py
  decide/store/views.py
  decide/users/views.py
  decide/visualizer/templates/visualizer/visualizer.html
  decide/visualizer/tests.py
  decide/visualizer/views.py
  decide/voting/admin.py
  decide/voting/management/commands/testvoting.py
  decide/voting/models.py
  decide/voting/serializers.py
  decide/voting/tests.py
  decide/voting/views.py
Labels: enhancement, Chiquito-2
